### ISSUE TITLE
Very high cardinality on metrics

### ISSUE THREAD

**Issue by skandragon** [Cyprinus12138/otelgin#3]
The HTTP metrics histogram has a lot of things that in a production environment are likely not useful, and will cause memory bloat.

```http_server_request_duration_milliseconds_bucket{http_method="POST",http_route="/api/v2/series",http_scheme="http",http_status_code="202",http_target="/api/v2/series",net_host_name="datadog-receiver",net_host_port="8080",net_protocol_version="1.1",net_sock_peer_addr="10.43.128.181",net_sock_peer_port="51112",otel_scope_name="github.com/Cyprinus12138/otelgin",otel_scope_version="0.49.0",user_agent_original="datadog-agent/7.52.0",le="0"} 0```

The `net_sock_peer_addr` and `net_sock_peer_port` and `user_agent_original` is likely to make pain happen when there are millions of unique combinations of these items.

Perhaps a way to filter the metrics as an option, either by marking what to include or exclude might be useful?

It's probably OK for traces, as those are more or less stand-alone, but the size metrics would generally be used per-endpoint I would think, not per something-the-user-controls-and-can-explode-my-server-memory.

If you'd like me to take a stab at this, I'm likely to implement a callback function that will take the metric keys and return a new list that has whatever I want in there.  This would allow me to filter as well as add should I want to.

**Comment by skandragon** [comment]
Or, I could use the already-metric friendly `HTTPServerRequestMetric()` call, which I suspect was your intention.

pr #4

**Comment by Cyprinus12138** [comment]
Hi @skandragon ! Yes, that's a really good point! I've sent you an invitation to join as a collaborator if you're interested. 
Thanks a lot for your contribution!

**Comment by skandragon** [comment]
Thanks for the offer :). I'm happy to, but would still like you to approve anything that isn't a typo style fix, especially if it changes behavior.
